2023-08-18 19:57:47,871 - DEBUG - pffrocd config: {
    "client": {
        "ip_address": "192.168.0.103",
        "username": "kamil",
        "private_ssh_key_path": "/home/kamil/.ssh/id_rsa",
        "executable_path": "/home/kamil/pffrocd/ABY/build/bin",
        "executable_name": "cos_dist_float_scen_simd",
        "pffrocd_path": "/home/kamil/pffrocd"
    },
    "server": {
        "ip_address": "192.168.0.106",
        "username": "kamil",
        "private_ssh_key_path": "/home/kamil/.ssh/id_rsa",
        "executable_path": "/home/kamil/pffrocd/ABY/build/bin",
        "executable_name": "cos_dist_float_scen_simd",
        "pffrocd_path": "/home/kamil/pffrocd"
    },
    "misc": {
        "nr_of_people": "1000",
        "security_level": "112",
        "mt_algorithm": "0",
        "niceness": "-20",
        "starting_person": "1"
    }
}
2023-08-18 19:57:48,513 - INFO - RUNNING for 999 people
2023-08-18 19:57:48,514 - INFO - Currently running for lfw/Aaron_Sorkin (1/999)
2023-08-18 19:57:48,514 - DEBUG - Found 2 images for lfw/Aaron_Sorkin
2023-08-18 19:57:48,514 - DEBUG - setting image as reference image: lfw/Aaron_Sorkin/Aaron_Sorkin_0001.jpg
2023-08-18 19:57:53,524 - DEBUG - Running test for lfw/Aaron_Sorkin/Aaron_Sorkin_0002.jpg
2023-08-18 19:57:58,136 - DEBUG - Stdout of extracting embedding: Directory  /home/kamil /.deepface created
Directory  /home/kamil /.deepface/weights created
sface weights will be downloaded...
2023-08-18 19:57:58,137 - DEBUG - Stderr of extracting embedding: Downloading...
From: https://github.com/opencv/opencv_zoo/raw/master/models/face_recognition_sface/face_recognition_sface_2021dec.onnx
To: /home/kamil/.deepface/weights/face_recognition_sface_2021dec.onnx
0.00B [00:00, ?B/s]222kB [00:00, 338MB/s]
Traceback (most recent call last):
  File "/home/kamil/pffrocd/pyscripts/extract_embedding.py", line 21, in <module>
    embedding = DeepFace.represent(input_image, model_name='SFace', enforce_detection=False)[0]["embedding"]
  File "/home/kamil/pffrocd/env/lib/python3.10/site-packages/deepface/DeepFace.py", line 639, in represent
    model = build_model(model_name)
  File "/home/kamil/pffrocd/env/lib/python3.10/site-packages/deepface/DeepFace.py", line 80, in build_model
    model = model()
  File "/home/kamil/pffrocd/env/lib/python3.10/site-packages/deepface/basemodels/SFace.py", line 51, in load_model
    model = SFaceModel(model_path=file_name)
  File "/home/kamil/pffrocd/env/lib/python3.10/site-packages/deepface/basemodels/SFace.py", line 19, in __init__
    self.model = cv.FaceRecognizerSF.create(
cv2.error: OpenCV(4.7.0) /io/opencv/modules/dnn/src/onnx/onnx_importer.cpp:275: error: (-210:Unsupported format or combination of formats) Failed to parse ONNX model: /home/kamil/.deepface/weights/face_recognition_sface_2021dec.onnx in function 'ONNXImporter'
